#if !defined FROZEN_META_STRING_BOOST_MPL_COMPATIBILITY_HPP_INCLUDED
#define      FROZEN_META_STRING_BOOST_MPL_COMPATIBILITY_HPP_INCLUDED



#endif    // FROZEN_META_STRING_BOOST_MPL_COMPATIBILITY_HPP_INCLUDED
