#if !defined FROZEN_MACROS_HPP_INCLUDED
#define      FROZEN_MACROS_HPP_INCLUDED

#if !defined FROZEN_STRING_LITERALS_MAX_LENGTH
#    define FROZEN_STRING_LITERALS_MAX_LENGTH 256
#endif

#endif    // FROZEN_MACROS_HPP_INCLUDED
