#if !defined FROZEN_STRING_DETAIL_MACROS_HPP_INCLUDED
#define      FROZEN_STRING_DETAIL_MACROS_HPP_INCLUDED

#if !defined FROZEN_STRING_LITERALS_MAX_LENGTH
#    define FROZEN_STRING_LITERALS_MAX_LENGTH 256
#endif

#if (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 6))
#    define FROZEN_CONSTEXPR_MATH_FUNCTIONS_ARE_AVAILABLE
#endif

#define FROZEN_ADD_PAREN(...) ((__VA_ARGS__))

#define FROZEN_NOEXCEPT_DEPENDS_ON_IMPL(expr) noexcept(noexcept(expr))
#define FROZEN_NOEXCEPT_DEPENDS_ON(...) FROZEN_NOEXCEPT_DEPENDS_ON_IMPL(FROZEN_ADD_PAREN(__VA_ARGS__))

#define FROZEN_STATIC_ASSERT_IMPL(expr)     static_assert(expr, #expr)
#define FROZEN_STATIC_ASSERT(...)           FROZEN_STATIC_ASSERT_IMPL(FROZEN_ADD_PAREN(__VA_ARGS__))
#define FROZEN_STATIC_ASSERT_NOT_IMPL(expr) static_assert(!expr, #expr)
#define FROZEN_STATIC_ASSERT_NOT(...)       FROZEN_STATIC_ASSERT_NOT_IMPL(FROZEN_ADD_PAREN(__VA_ARGS__))

#endif    // FROZEN_STRING_DETAIL_MACROS_HPP_INCLUDED
